name: Build Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'latest'

    - name: Install mingw-w64 for Windows cross-compilation
      run: sudo apt-get install -y gcc-mingw-w64-x86-64

    - name: Validate Windows build
      run: |
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 \
        CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ \
        go build -v -o /dev/null ./...

