name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with "v"
  workflow_dispatch:  # Adds a manual trigger option
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true

    - name: Install mingw-w64 for Windows cross-compilation
      run: sudo apt-get install -y gcc-mingw-w64-x86-64

    - name: Build Windows executable
      run: |
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 \
        CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ \
        go build -v -o goDatalogConvert.exe

    - name: Archive Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: goDatalogConvert-windows-${{ github.ref_name }}
        path: goDatalogConvert.exe


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Windows binary artifact
      uses: actions/download-artifact@v4
      with:
        name: goDatalogConvert-windows-${{ github.ref_name }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Windows binary to Release using GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} goDatalogConvert.exe --clobber
